version: "3.9"

secrets:
  nginx-crt:
    file: ${NGINX_CERT}
  nginx-key:
    file: ${NGINX_KEY}

services:
  nap-compiler:
    image: nap-compiler
    build:
      context: ../../
      dockerfile: ./Dockerfile
      secrets:
        - nginx-crt
        - nginx-key
    container_name: "nap-compiler"
    ports:
      - "6000:5000"
    networks:
      - nap-compiler

networks:
  nap-compiler:
